/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../contexts/ConfessionContext`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/after-prayers` | `/after-prayers`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/document` | `/document`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/guide` | `/guide`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/prayers` | `/prayers`; params?: Router.UnknownInputParams; } | { pathname: `/constants/colors`; params?: Router.UnknownInputParams; } | { pathname: `/constants/confessionItems`; params?: Router.UnknownInputParams; } | { pathname: `/constants/prayers`; params?: Router.UnknownInputParams; } | { pathname: `/contexts/ConfessionContext`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/../contexts/ConfessionContext`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/after-prayers` | `/after-prayers`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/document` | `/document`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/guide` | `/guide`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/prayers` | `/prayers`; params?: Router.UnknownOutputParams; } | { pathname: `/constants/colors`; params?: Router.UnknownOutputParams; } | { pathname: `/constants/confessionItems`; params?: Router.UnknownOutputParams; } | { pathname: `/constants/prayers`; params?: Router.UnknownOutputParams; } | { pathname: `/contexts/ConfessionContext`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/../contexts/ConfessionContext${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/after-prayers${`?${string}` | `#${string}` | ''}` | `/after-prayers${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/document${`?${string}` | `#${string}` | ''}` | `/document${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/guide${`?${string}` | `#${string}` | ''}` | `/guide${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/prayers${`?${string}` | `#${string}` | ''}` | `/prayers${`?${string}` | `#${string}` | ''}` | `/constants/colors${`?${string}` | `#${string}` | ''}` | `/constants/confessionItems${`?${string}` | `#${string}` | ''}` | `/constants/prayers${`?${string}` | `#${string}` | ''}` | `/contexts/ConfessionContext${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../contexts/ConfessionContext`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/after-prayers` | `/after-prayers`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/document` | `/document`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/guide` | `/guide`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/prayers` | `/prayers`; params?: Router.UnknownInputParams; } | { pathname: `/constants/colors`; params?: Router.UnknownInputParams; } | { pathname: `/constants/confessionItems`; params?: Router.UnknownInputParams; } | { pathname: `/constants/prayers`; params?: Router.UnknownInputParams; } | { pathname: `/contexts/ConfessionContext`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
